name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Ramesh KHARAT'
          git config --global user.email 'ramesh@priarworld.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/repo2
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Automated report"
          git push
